import {permanentHelp} from './in-service/permanent/help';
/** Explanations shared by input labels; no numerical assumptions are supplied here. */
const hints:[RegExp,string][]=[
 [/^NPS/, 'Nominal pipe size. Choosing a size supplies its standard outside diameter; use Custom for a measured diameter.'],
 [/^Schedule/, 'Standard wall-thickness series for the selected pipe size. Verify the actual applicable wall thickness.'],
 [/^(D₀|Outside diameter)/,'Outside steel diameter, excluding coating. Units follow the SI/Imperial selector.'],
 [/^(t \(|Analysis thickness)/,'Uniform steel wall used by the mechanical model. Local corrosion, thinning and defects are not assessed.'],
 [/^Steel Grade/,'Supplies a yield-strength starting value. Confirm the material properties applicable to your pipe and temperature.'],
 [/^(Yield|Specified SMYS)/,'Yield strength is the stress where plastic deformation starts. Specified SMYS for CSA is a separate design input; confirm the material specification.'],
 [/^Young/,'Elastic stiffness of steel. A higher modulus increases forces required for the same imposed deformation. Check the displayed pressure unit.'],
 [/^Poisson/,'Dimensionless ratio of transverse contraction to axial extension. Used in the pressure/axial stress relationship.'],
 [/^Thermal expansion/,'Change in strain per degree of temperature change. The displayed value is in millionths per degree; restraint converts thermal expansion into axial force.'],
 [/^Internal gauge pressure/,'Operating pressure above atmospheric pressure, held constant through the intervention. It is not automatically the CSA design pressure.'],
 [/^Operating temperature/,'Uniform pipe temperature during the intervention. Thermal force also depends on the initial reference temperature.'],
 [/^(Steel density|Density ρ)/,'Mass per volume of steel, used to calculate self-weight. This is not the fluid or coating density.'],
 [/^Fluid density/,'Fluid mass per volume at operating pressure and temperature. Used for contained-fluid weight.'],
 [/^Fluid$/,'Choose a gas-density model or enter a known density. The natural-gas preset starts with methane molar mass; gas composition must be checked.'],
 [/^Molar mass/,'Average molar mass of the gas mixture, in g/mol. Used with absolute pressure, temperature and Z to calculate density.'],
 [/^Compressibility/,'Dimensionless gas factor Z. Z = 1 is ideal gas; enter a suitable real-gas value for the operating conditions.'],
 [/^Atmospheric/,'Added to gauge pressure to obtain the absolute pressure used by the gas-density model.'],
 [/^Include self-weight/,'Adds gravity loading based on steel density and section area. Review coating weight separately.'],
 [/^Type$/,'Coating material preset. Coating contributes weight, not pipe stiffness; confirm preset density and thickness.'],
 [/^Thickness/,'Coating thickness outside the steel wall. Used to calculate additional distributed weight only.'],
 [/^Density \(/,'Mass per volume of coating, used with coating thickness to calculate added weight.'],
 [/^L \(/,'Total analysed length between the fixed ends. This differs from the half-length input in the in-service module.'],
 [/^Length on each side/,'Distance from the central actuator to either fixed end. Total excavated length is twice this value.'],
 [/^(Min\.|Max\.) length each side/,'Exploratory search bound for one half of the excavation. Unresolved and unsampled regions are not verified.'],
 [/^Search (minimum|maximum) length/,'Bounds of the total-length exploratory search. An unsuccessful search does not prove all lengths impossible.'],
 [/^(Represented|Custom L|Custom hv|Estimated admissible|Admissible ranges)/,'Select the candidate to display and verify. Estimated ranges may contain unresolved regions; export uses the current verified calculation snapshot.'],
 [/^Minimum pipe-axis/,'Lowest allowed elevation of the pipe axis, not the ground surface. Pipe radius is already accounted for in this value.'],
 [/^Axial mode/,'Free sliding has no axial restraint. Restrained uses its coupled axial/geometric-stiffness solver and combined-stress criterion.'],
 [/^Installed supports/,'Number of equally spaced unilateral vertical supports. Contact may be lost; these are not imposed vertical fixities.'],
 [/^Search ceiling/,'Largest support count explored under the shared search budget. This is a search limit, not a guarantee of feasibility.'],
 [/^Calculation$/,'Direct calculation assesses the entered geometry; searches explore candidate lengths, displacements or support counts using the custom criterion.'],
 [/^Direction$/,'Vertical leaves lateral motion free; horizontal leaves vertical sag free; combined prescribes both components.'],
 [/^Sense$/,'Sign of the commanded movement: upward/downward or positive/negative model lateral direction.'],
 [/^Direction angle/,'Angle of imposed movement: 0 degrees is positive lateral, 90 degrees is upward. The amplitude resolves into these two components.'],
 [/^Target amplitude/,'Magnitude of the target centre displacement from the original straight pipe axis, not from the sagged position after excavation.'],
 [/^Search amplitude/,'Maximum movement magnitude explored. Reaching this bound does not prove a physical maximum displacement.'],
 [/^(Layout|Support layout)$/,'Temporary frictionless supports provide upward reaction only and allow lift-off and sliding. They do not provide lateral restraint.'],
 [/^Support search ceiling/,'Largest even support count explored: 0, 2, 4 and so on. The central actuator is not counted as a support.'],
 [/^Number of supports/,'Even number of equidistant temporary supports; the centre is reserved for the actuator.'],
 [/^Layout reference/,'Reference half-length used to enter support positions. During a length search, their relative positions are preserved.'],
 [/^Support \d+ from/,'Distance from the left fixed end. Both end clamps and the central actuator must be excluded. Positions scale with total length.'],
 [/^(Allowable|Safety factor|Threshold format)/,'Custom stress threshold, not a normative compliance certificate. Percentage and safety factor express the same limit: yield divided by safety factor.'],
 [/^Reference temperature/,'Hypothesized stress-free thermal reference for this initial state. It is not automatically the CSA anchoring temperature.'],
 [/^Extra axial force/,'Additional wall force only: positive tension, negative compression. Do not include pressure or thermal contributions already modeled.'],
 [/^Scenario name/,'Identify an initial-state hypothesis. All supplied scenarios are checked; a name does not establish that its assumptions are known.'],
 [/^Design gauge pressure/,'CSA design pressure above atmospheric pressure. Enter separately and ensure it covers the intervention operating pressure.'],
 [/^Maximum design temperature/,'CSA maximum design temperature, separately specified. Temperature-factor evaluation does not extrapolate beyond 230 degrees C.'],
 [/^Temperature at anchoring/,'Pipe temperature when axial restraint was established for the CSA design state. Not inferred from the mechanical reference temperature.'],
 [/^Nominal thickness/,'Nominal steel wall for the CSA checks, distinct from mechanical analysis thickness.'],
 [/^Allowance/,'Applicable wall allowance under CSA 4.3.10, subtracted from nominal wall for the anchored check. Enter zero explicitly only when justified.'],
];
export function fieldHelp(label:string):string|undefined{return permanentHelp(label.trim())??hints.find(([pattern])=>pattern.test(label.trim()))?.[1];}
