import {it,expect} from 'vitest';
import {permanentFixture} from './fixture';
import {constructionPath,runPermanent} from '../sequence';
import {validatePermanent} from '../profile';
it('requires complete site inputs, and accepts an explicit verification fixture',()=>{const i=permanentFixture();expect(validatePermanent(i)).toEqual([]);i.permanent.zones[0].axial.source='';expect(validatePermanent(i).length).toBeGreaterThan(0);});
it.each(['before','after'] as const)('completes %s release without residual equipment or support reactions',release=>{const i=permanentFixture();i.permanent.release=release;const r=constructionPath(i,i.scenarios[0],16,4,()=>{});expect(r.status,r.message).toBe('complete');expect(r.final.state.contacts).toEqual([]);const mid=r.final.mesh.indexOf(i.halfLength);expect(r.final.state.reactions[5*mid+1]).toBeCloseTo(0,4);expect(r.heights.length).toBe(1);expect(r.operations.length).toBe(1);});
it('refines the full sequence',()=>{const i=permanentFixture();i.supports={kind:'custom',fractions:[.25,.75]};const r=runPermanent(i,()=>{}).scenarios[0];expect(r.status,r.message).toBe('complete');expect(r.mechanical).toBe('satisfied');expect(r.position).toBe('satisfied');expect(r.final).toBeDefined();},60000);
it('reports lateral rebound when equipment is released before soil engagement',()=>{const i=permanentFixture();i.direction='horizontal';i.permanent.release='before';const r=constructionPath(i,i.scenarios[0],16,4,()=>{});expect(r.status,r.message).toBe('complete');const m=r.released.mesh.indexOf(i.halfLength);expect(Math.abs(r.released.state.d[5*m+3])).toBeLessThan(1e-5);});
it('retains elastic stress after backfill and records soil limits without approval',()=>{const i=permanentFixture();const r=constructionPath(i,i.scenarios[0],16,4,()=>{});expect(r.final.state.vm).toBeGreaterThan(1);i.permanent.zones[0].down.points[1]={displacement:1e-6,reaction:1e-6};const limited=constructionPath(i,i.scenarios[0],16,4,()=>{});expect(limited.soilLimited).toBe(true);expect(limited.position).not.toBe('satisfied');});
it('handles common support heights and a separate symmetric support arrangement',()=>{const i=permanentFixture();i.permanent.reusePositions=false;i.permanent.pairs=[.4,.2];i.permanent.heightMode='common';i.permanent.heights=[8,4];i.permanent.removalOrder=[1,0];const r=constructionPath(i,i.scenarios[0],16,4,()=>{});expect(r.status,r.message).toBe('complete');expect(r.heights).toEqual([8,4]);expect(r.stages.findIndex(s=>s.name.startsWith('Remove pair 2'))).toBeLessThan(r.stages.findIndex(s=>s.name.startsWith('Remove pair 1')));});
it('preserves partial results after a computational budget stop',()=>{const i=permanentFixture();let calls=0;const r=constructionPath(i,i.scenarios[0],16,4,()=>{if(++calls>50)throw new Error('budget exhausted');});expect(r.status).toBe('unresolved');expect(r.mechanical).toBe('not evaluated');expect(r.message).toContain('budget');});
it('rejects asymmetric initial supports, missing soil data and invalid common settings',()=>{const i=permanentFixture();i.supports={kind:'custom',fractions:[.2]};expect(validatePermanent(i).join()).toContain('symmetric');i.permanent.heightMode='common';expect(validatePermanent(i).join()).toContain('height');i.permanent.operations=[];expect(validatePermanent(i).join()).toContain('operating');});

it('keeps a nonconverged third-span support example unresolved',()=>{const r=runPermanent(permanentFixture(),()=>{}).scenarios[0];expect(r.status).toBe('unresolved');expect(r.mechanical).toBe('not evaluated');},60000);
