import {Field} from './ServiceInputs';
import {Input} from '../ui/input';
import {Button} from '../ui/button';
import FieldHelp from '../FieldHelp';
import type {ServiceInput} from '@/lib/in-service/types';
import {defaultPermanent,emptyZone,pairs,type PermanentProfile,type SoilCurve} from '@/lib/in-service/permanent/profile';
const cls='w-full rounded-md border border-input bg-background p-2 text-sm';
export default function PermanentInputs({input:i,onChange}:{input:ServiceInput;onChange:(v:ServiceInput)=>void}){
 const p=i.permanent??defaultPermanent(),set=(v:PermanentProfile)=>onChange({...i,permanent:v});
 const selection=<K extends keyof PermanentProfile>(key:K,title:string,options:[string,string][])=> <label className="block text-sm">{title}<select className={cls} value={String(p[key])} onChange={e=>set({...p,[key]:e.target.value})}>{options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>;
 const curve=(v:SoilCurve,change:(v:SoilCurve)=>void,name:string)=><details className="border rounded p-2"><summary>{name} resistance law</summary><p className="text-xs my-2">Positive relative movement and distributed resistance. Starts at zero. Last point is the documented limit, not permission to continue after soil failure. Symmetric for axial/lateral; separate down/up laws.</p><label className="text-xs">Source / justification<Input value={v.source} onChange={e=>change({...v,source:e.target.value})}/></label>{v.points.map((pt,k)=><div key={k} className="grid grid-cols-[1fr_1fr_auto] gap-1 mt-2"><Field title={`${name} displacement ${k+1}`} unit="mm" value={pt.displacement} onChange={x=>change({...v,points:v.points.map((a,j)=>j===k?{...a,displacement:x}:a)})}/><Field title={`${name} resistance ${k+1}`} unit="N/mm" value={pt.reaction} onChange={x=>change({...v,points:v.points.map((a,j)=>j===k?{...a,reaction:x}:a)})}/><Button variant="ghost" disabled={k===0||v.points.length<=2} onClick={()=>change({...v,points:v.points.filter((_,j)=>j!==k)})} aria-label={`Remove ${name} point ${k+1}`}>×</Button></div>)}<Button className="mt-2" variant="outline" disabled={v.points.length>=30} onClick={()=>change({...v,points:[...v.points,{displacement:NaN,reaction:NaN}]})}>Add point</Button></details>;
 const ps=i.permanent?pairs(i):[],order=p.removalOrder.length?p.removalOrder:ps.map((_,j)=>j);
 return <section className="border rounded-lg bg-card p-4 space-y-4"><h2 className="font-semibold">Intervention type</h2><select aria-label="Intervention type" className={cls} value={i.intervention??'temporary'} onChange={e=>onChange({...i,intervention:e.target.value as ServiceInput['intervention'],permanent:p,mode:'direct'})}><option value="temporary">Temporary intervention</option><option value="permanent">Permanent maintained deviation · elastic steel</option></select>
 {i.intervention==='permanent'&&<><p className="text-sm text-amber-700 dark:text-amber-400">Numerically benchmarked elastic model. Site applicability requires separate assessment. No permanent installation approval.</p><p className="text-xs">Direct calculation only. Supports are vertical, upward-only, with free axial/lateral sliding. Soil curves are reversible; irreversible soil slip, consolidation, fatigue, welds and local buckling are not assessed.</p>
 <label className="flex gap-2 text-sm"><input type="checkbox" checked={p.clampsConfirmed} onChange={e=>set({...p,clampsConfirmed:e.target.checked})}/>Ideal clamps represent the adjacent buried pipe.</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={p.propertiesConfirmed} onChange={e=>set({...p,propertiesConfirmed:e.target.checked})}/>Entered steel properties apply to all temperatures below.</label>
 {selection('initialSupports','Initial supports during movement',[['keep','Keep at original height'],['remove','Unload and remove before movement']])}
 {selection('release','Release equipment',[['before','Before backfill'],['after','After backfill']])}
 <label className="flex gap-2 text-sm"><input type="checkbox" checked={p.reusePositions} onChange={e=>set({...p,reusePositions:e.target.checked,removalOrder:[],heights:[]})}/>Reuse initial support positions<FieldHelp text="Positions are reused, not their loads. Existing supports are unloaded under equipment control before repositioning. Symmetric pairs are required."/></label>
 {!p.reusePositions&&<div className="space-y-2"><p className="text-xs">Left position as a fraction of full span, between 0 and 0.5. Right position is its mirror. Pairs are numbered from centre outward.</p>{p.pairs.map((v,j)=><div className="flex gap-2" key={j}><Field title={`Pair position ${j+1}`} value={v} onChange={x=>set({...p,pairs:p.pairs.map((a,k)=>k===j?x:a),removalOrder:[],heights:[]})}/><Button variant="ghost" onClick={()=>set({...p,pairs:p.pairs.filter((_,k)=>k!==j),removalOrder:[],heights:[]})}>×</Button></div>)}<Button variant="outline" disabled={p.pairs.length>=10} onClick={()=>set({...p,pairs:[...p.pairs,NaN],removalOrder:[],heights:[]})}>Add pair</Button></div>}
 {selection('heightMode','Support setting',[['fitted','Fit to each scenario: no added preload'],['common','Common absolute heights for every scenario']])}
 <p className="text-xs">Heights refer to the pipe axis relative to its original position, not jack extension or ground elevation. Common heights can introduce a calculated preload; fitting automatically to each scenario does not verify one common physical setting.</p>
 {p.heightMode==='common'&&ps.map((f,j)=><Field key={f} title={`Pair ${j+1} height (x/L ${f.toFixed(4)})`} unit="mm" value={p.heights[j]??NaN} onChange={v=>{const heights=ps.map((_,k)=>p.heights[k]??NaN);heights[j]=v;set({...p,heights});}}/>)}
 <p className="text-sm">Pair removal order (centre outward by default)</p>{order.map((v,j)=><div key={j} className="flex gap-2 items-center text-sm"><span>{j+1}. Pair {v+1}</span><Button variant="outline" disabled={j===0} onClick={()=>{const a=[...order];[a[j-1],a[j]]=[a[j],a[j-1]];set({...p,removalOrder:a});}}>Move earlier</Button></div>)}
 <div className="grid grid-cols-2 gap-2"><Field title="Final vertical tolerance" unit="mm" value={p.verticalTolerance} onChange={v=>set({...p,verticalTolerance:v})}/><Field title="Final lateral tolerance" unit="mm" value={p.lateralTolerance} onChange={v=>set({...p,lateralTolerance:v})}/></div><p className="text-xs">Tolerances apply at the centre in controlled directions, after equipment/support removal and throughout each listed operating transition. Uncontrolled-direction movement is reported separately.</p>
 <h3 className="font-medium">Backfill zones</h3><p className="text-xs">Zones must cover 0–1 without gaps or overlap. Equal stage numbers activate together. Downward loads are separate from soil resistance. Bed gap is below the current pipe axis when the zone is activated.</p>
 {p.zones.map((z,j)=>{const change=(v:typeof z)=>set({...p,zones:p.zones.map((a,k)=>k===j?v:a)});return <details key={j} open className="border rounded p-3 space-y-3"><summary>Zone {j+1}: {z.name}</summary><label className="text-xs">Zone name<Input value={z.name} onChange={e=>change({...z,name:e.target.value})}/></label><div className="grid grid-cols-2 gap-2"><Field title="Start x/L" value={z.start} onChange={v=>change({...z,start:v})}/><Field title="End x/L" value={z.end} onChange={v=>change({...z,end:v})}/><Field title="Activation stage" value={z.step} onChange={v=>change({...z,step:v})}/><Field title="Initial bed gap" unit="mm" value={z.bedOffset} onChange={v=>change({...z,bedOffset:v})}/><Field title="Permanent backfill load" unit="N/mm" value={z.weight} onChange={v=>change({...z,weight:v})}/><Field title="Temporary construction load" unit="N/mm" value={z.construction} onChange={v=>change({...z,construction:v})}/></div>{(['axial','lateral','down','up'] as const).map(k=><div key={k}>{curve(z[k],v=>change({...z,[k]:v}),k)}</div>)}<Button variant="outline" onClick={()=>set({...p,zones:p.zones.filter((_,k)=>k!==j)})}>Remove zone</Button></details>;})}<Button variant="outline" disabled={p.zones.length>=20} onClick={()=>set({...p,zones:[...p.zones,emptyZone()]})}>Add zone</Button>
 <h3 className="font-medium">Future operating cases</h3><p className="text-xs">Each case starts independently from the final backfilled state. Explicit fluid density is required at its pressure and temperature. These are not a fatigue spectrum or a complete operating envelope.</p>{p.operations.map((o,j)=>{const change=(v:typeof o)=>set({...p,operations:p.operations.map((a,k)=>k===j?v:a)});return <div key={j} className="border rounded p-2 space-y-2"><label className="text-xs">Case name<Input value={o.name} onChange={e=>change({...o,name:e.target.value})}/></label><Field title="Gauge pressure" value={o.pressure} unit="pressure" onChange={v=>change({...o,pressure:v})}/><Field title="Temperature" value={o.temperature} unit="C" onChange={v=>change({...o,temperature:v})}/><Field title="Fluid density" value={o.fluidDensity} unit="kg/m3" onChange={v=>change({...o,fluidDensity:v})}/><Button variant="outline" onClick={()=>set({...p,operations:p.operations.filter((_,k)=>k!==j)})}>Remove case</Button></div>;})}<Button variant="outline" disabled={p.operations.length>=12} onClick={()=>set({...p,operations:[...p.operations,{name:`Operating case ${p.operations.length+1}`,pressure:NaN,temperature:NaN,fluidDensity:NaN}]})}>Add operating case</Button>
 </>}
 </section>;
}
