import {buildPdfFileName} from '@/lib/pdf/file-name';
import {useState} from 'react';
import {useUnits} from '@/contexts/UnitContext';
import {format} from '@/lib/in-service/display';
import type {ServiceReport} from '@/lib/in-service/types';
import type {IdentityFields} from '../ReportIdentityFields';
import {Button} from '../ui/button';
import {printPdfPalette} from '@/lib/in-service/pdf-theme';
import {createPermanentPdf,PERMANENT_LIMITS,milestoneRows,permanentPeaks,governingMetrics} from '@/lib/in-service/permanent/report';
import {pairs} from '@/lib/in-service/permanent/profile';
import {ServiceCsaResults} from './ServiceCsa';
export default function PermanentResults({report:r,identity}:{report:ServiceReport;identity:IdentityFields}){
 const {system}=useUnits(),[selected,setSelected]=useState<Record<string,number>>({}),[error,setError]=useState(''),i=r.input,p=i.permanent;
 const f=(v:number,u:Parameters<typeof format>[1])=>format(v,u,system);
 return <div className="space-y-4"><section className="border rounded-lg p-4 space-y-3 bg-card"><h2 className="text-lg font-semibold">Permanent elastic assessment</h2><p role="status">{r.message}</p><p className="text-amber-700 dark:text-amber-400">Numerically benchmarked elastic model. Site applicability and excluded integrity checks require separate assessment. No permanent installation approval.</p><div className="flex gap-2">{[false,true].map(complete=><Button key={String(complete)} disabled={!identity.preparedBy.trim()||!identity.projectName.trim()} variant={complete?'outline':'default'} onClick={()=>{try{const meta={...identity,date:new Date()};createPermanentPdf(r,system,printPdfPalette(),meta,complete).save(buildPdfFileName('in-serv-perm',meta.preparedBy,meta.date,complete?'complete':'summary')+'.pdf');setError('');}catch(e){setError(String(e));}}}>{complete?'Complete':'Summary'} PDF</Button>)}</div>{error&&<p role="alert">{error}</p>}{r.budgetExhausted&&<p>Calculation budget exhausted; incomplete results remain unresolved.</p>}</section><ServiceCsaResults assessment={r.csa}/>
 {r.permanent.scenarios.map(s=>{const index=selected[s.scenario.id]??Math.max(0,s.stages.indexOf(s.final??s.stages.at(-1))),st=s.stages[index];const mid=st?.mesh.indexOf(i.halfLength);return <section key={s.scenario.id} className="border rounded-lg bg-card p-4 space-y-4"><h3 className="font-semibold">{s.scenario.name}</h3><p>{s.message}</p><dl className="grid sm:grid-cols-2 gap-3 text-sm">{[['Sequence',s.status],['Custom stress criterion',s.mechanical],['Final centre position',s.position],['Soil resistance limit',s.soilLimited?'Reached: retention not verified':'No detected limit in computed states']].map(([a,b])=><div key={a}><dt className="text-muted-foreground">{a}</dt><dd className="font-medium">{b}</dd></div>)}</dl>
 <div className="overflow-auto"><table className="w-full text-sm"><thead><tr><th className="text-left">Milestone</th><th>Vertical centre</th><th>Lateral centre</th><th>Stress bound</th></tr></thead><tbody>{milestoneRows(s).map((v,j)=>{const m=v.mesh.indexOf(i.halfLength);return <tr className="border-b" key={j}><td className="py-2">{v.name}</td><td>{f(v.state.d[5*m+1],'mm')}</td><td>{f(v.state.d[5*m+3],'mm')}</td><td>{f(v.state.vm,'MPa')}</td></tr>;})}</tbody></table></div>
 <p className="text-xs">Position acceptance concerns the centre in controlled directions, at final state and during listed operating transitions. Uncontrolled-direction movement is shown but is not compared to an imposed target. Soil limits and incomplete convergence prevent a verified retention result.</p>
 <details><summary>Maximum demands and governing stages</summary>{governingMetrics(s).map(v=><p key={v.label} className="text-sm">{v.label}: {f(v.value,v.unit)} · {v.stage}</p>)}</details><h4 className="font-medium">Support settings</h4><p className="text-xs">{p.heightMode==='fitted'?'These heights fit this scenario. Different heights across scenarios do not verify a single common physical setting.':'Common prescribed heights; any positioning preload is included.'} Positive height is above the original pipe axis.</p>{pairs(i).map((v,j)=><p key={j} className="text-sm">Pair {j+1}: x = {f(2*i.halfLength*v/1000,'m')} and {f(2*i.halfLength*(1-v)/1000,'m')} · height {f(s.heights[j],'mm')}</p>)}
 {st&&<><label className="block text-sm">Construction and operation timeline<select className="w-full border rounded p-2 bg-background" value={index} onChange={e=>setSelected({...selected,[s.scenario.id]:Number(e.target.value)})}>{s.stages.map((v,j)=><option key={j} value={j}>{v.name} · {(100*v.fraction).toFixed(2)}%</option>)}</select></label><p className="text-sm">Selected: {st.name}. Centre vertical {f(st.state.d[5*mid+1],'mm')}, lateral {f(st.state.d[5*mid+3],'mm')}. Equipment forces: vertical {f(st.equipment[0],'N')}, lateral {f(st.equipment[1],'N')}.</p>
 <div className="grid sm:grid-cols-2 gap-3">{([1,3] as const).map(axis=>{const profiles=[{stage:s.target,color:'#f59e0b'},{stage:s.final,color:'#3b82f6'},{stage:st,color:'#10b981'}].filter(v=>v.stage),values=profiles.flatMap(v=>v.stage.mesh.map((_,j)=>v.stage.state.d[5*j+axis])),lo=Math.min(0,...values),hi=Math.max(0,...values),x=(v:number)=>30+v/(2*i.halfLength)*540,y=(v:number)=>150-(v-lo)/(hi-lo||1)*120;return <figure key={axis}><figcaption>{axis===1?'Vertical':'Lateral'} profile</figcaption><svg viewBox="0 0 600 180" className="w-full" role="img" aria-label="Target, final and selected profiles"><line x1="30" x2="570" y1={y(0)} y2={y(0)} stroke="currentColor" strokeDasharray="5 4"/>{profiles.map((v,k)=><path key={k} d={v.stage.mesh.map((m,j)=>`${j?'L':'M'}${x(m)},${y(v.stage.state.d[5*j+axis])}`).join(' ')} fill="none" stroke={v.color} strokeWidth="2"/>)}{axis===1&&st.state.contacts.map(c=><path key={c.id} d={`M${x(st.mesh[c.node])} ${y(c.height)}l-5 8h10Z`} fill="#10b981"/>)}<text x="30" y="175" fill="currentColor" fontSize="12">{f(lo,'mm')} to {f(hi,'mm')}</text></svg></figure>;})}</div><p className="text-xs">Orange: imposed target. Blue: final backfilled state. Green: selected state. Deflection exaggerated.</p>
 <div className="overflow-auto"><table className="w-full text-xs"><thead><tr><th>Support</th><th>Reaction upward</th><th>Gap</th></tr></thead><tbody>{st.state.contacts.map(c=><tr key={c.id}><td>{c.id}</td><td>{f(c.reaction,'N')}</td><td>{f(c.gap,'mm')}</td></tr>)}</tbody></table></div>
 <details><summary>Soil reactions and axial force profile</summary><div className="max-h-80 overflow-auto"><table className="w-full text-xs"><thead><tr><th>Zone / axis</th><th>x</th><th>Reaction</th><th>Relative movement</th></tr></thead><tbody>{st.state.soil.map((v,j)=><tr key={j}><td>{v.zone} / {v.direction} {v.limited?'LIMIT':''}</td><td>{f(st.mesh[v.node]/1000,'m')}</td><td>{f(v.force,'N')}</td><td>{f(v.displacement,'mm')}</td></tr>)}</tbody></table>{st.state.axial.map((v,j)=><p key={j}>Element {j+1}: effective {f(v,'N')} / wall {f(v+st.pressure*Math.PI*(i.od/2-i.thickness)**2,'N')}</p>)}</div></details></>}
 <details><summary>Phase peaks and numerical refinement</summary>{permanentPeaks(s).map(v=><p key={v.name} className="text-xs">{v.name}: {f(v.state.vm,'MPa')} at {(100*v.fraction).toFixed(2)}%</p>)}{s.refinement.map(v=><p key={v.elements} className="text-xs">{v.elements} base elements / {v.increments} increments: {f(v.stress,'MPa')} · change {Number.isFinite(v.change)?`${(100*v.change).toFixed(4)}%`:'first level'}</p>)}</details>
 </section>;})}<p className="text-xs text-muted-foreground">{PERMANENT_LIMITS}</p></div>;
}
