import FieldHelp from '@/components/FieldHelp';
import {Field} from './ServiceInputs';
import {defaultSag} from '@/lib/in-service/sag-profile';
import type {ServiceInput} from '@/lib/in-service/types';
export default function SagInputs({input:i,onChange}:{input:ServiceInput;onChange:(i:ServiceInput)=>void}){
 const p=i.sag??defaultSag(),simple=p.boundary==='simple';
 const set=(v:typeof p)=>onChange({...i,sag:v});
 return <section className="rounded-lg border bg-card p-4 space-y-3"><h2 className="font-semibold">Sag only — one full span</h2>
 <label className="block text-xs">End conditions<FieldHelp text="Clamped ends prevent translation and rotation, including axial movement. Simple supports allow rotation and axial sliding at one end. A long pipe is not automatically clamped; a continuous multi-span pipe requires a different model."/><select aria-label="Sag end conditions" className="w-full rounded-md border bg-background p-2 text-sm" value={p.boundary} onChange={e=>set({...p,boundary:e.target.value as typeof p.boundary,confirmed:false})}><option value="clamped">Both ends clamped</option><option value="simple">Two simple supports — axial sliding free</option></select></label>
 <svg viewBox="0 0 300 95" role="img" aria-label="One full span L between level end supports, downward sag at the centre" className="w-full"><path d="M20 25H280" stroke="currentColor" fill="none" strokeDasharray="4 3"/><path d="M20 25 Q150 85 280 25" stroke="#3b82f6" fill="none" strokeWidth="3"/>{simple?<path d="M20 25 l-8 12 h16 Z M280 25 l-8 12 h16 Z" fill="none" stroke="currentColor"/>:<path d="M20 10V40 M280 10V40" stroke="currentColor" strokeWidth="5"/>}<path d="M20 78H280 M20 74V82 M280 74V82" stroke="currentColor"/><text x="100" y="93" fill="currentColor" fontSize="12">L = full span</text><text x="154" y="43" fill="currentColor" fontSize="12">sag ↓</text></svg>
 <label className="flex gap-2 text-xs"><input type="checkbox" aria-label="Sag boundary conditions confirmed" checked={p.confirmed} onChange={e=>set({...p,confirmed:e.target.checked})}/>These end conditions represent the installation.</label>
 <label className="block text-xs">Calculation<select aria-label="Sag calculation" className="w-full rounded-md border bg-background p-2 text-sm" value={i.mode} onChange={e=>onChange({...i,mode:e.target.value as 'direct'|'length'})}><option value="direct">Fixed L → calculate sag</option><option value="length">Find L → maximum admissible sag</option></select></label>
 {i.mode==='direct'?<Field title="Full span L" unit="m" value={i.halfLength/500} onChange={v=>onChange({...i,halfLength:v*500})} help="Distance between both end supports, not half-length. Example: 12 m for a pipe supported at both ends. Supports must be at the same level."/>:<div className="grid grid-cols-2 gap-2"><Field title="Minimum full span" unit="m" value={i.minHalfLength/500} onChange={v=>onChange({...i,minHalfLength:v*500})} help="Lower full-span bound for the exploratory search. No result is inferred outside these bounds."/><Field title="Maximum full span" unit="m" value={i.maxHalfLength/500} onChange={v=>onChange({...i,maxHalfLength:v*500})} help="Upper full-span search bound. Reaching it does not establish a physical maximum."/></div>}
 <Field title="Maximum admissible sag" unit="mm" value={p.limit??NaN} onChange={v=>set({...p,limit:Number.isNaN(v)?undefined:v})} help="Positive downward deflection from the straight line between end supports. Example: 50 mm. Required for Find L; optional for fixed L. This is an acceptance limit, never an imposed displacement."/>
 <p className="text-xs">No centre actuator, intermediate supports, overhangs, ground contact or backfill. Existing movement/support settings are retained but unused.</p>
 {simple&&<p className="text-xs">Zero gauge pressure and zero extra axial force required. Axial sliding allows thermal expansion without axial stress. Two vertical static lifting forces can be idealized here; inclined slings, dynamics and local lifting stresses are not assessed.</p>}
 </section>;
}
