import PermanentInputs from '@/components/in-service/PermanentInputs';
import ReportIdentityFields from '@/components/ReportIdentityFields';
import { ServiceCsaInputs } from '@/components/in-service/ServiceCsa';
import { useState } from 'react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { UnitProvider,useUnits } from '@/contexts/UnitContext';
import { Button } from '@/components/ui/button';
import { DEFAULT_SERVICE,type ServiceInput } from '@/lib/in-service/types';
import { ServiceInputs } from '@/components/in-service/ServiceInputs';
import { ServicePresets } from '@/components/in-service/ServicePresets';
import ServiceResults from '@/components/in-service/ServiceResults';
import { useServiceEngine } from '@/hooks/useServiceEngine';
function Workspace(){
  const [input,setInput]=useState<ServiceInput>(()=>structuredClone(DEFAULT_SERVICE));
  const [inputRevision,setInputRevision]=useState(0);
  const [identity,setIdentity]=useState({preparedBy:'',projectName:''});
  const engine=useServiceEngine();const {system,toggle}=useUnits();
  return <><div className="flex flex-wrap justify-between items-start gap-4"><div><p className="text-primary text-sm font-medium mb-2">Steel · Elastic intervention · Custom criteria</p><h1 className="text-2xl sm:text-3xl font-semibold">In-service pipe deflection</h1></div><Button variant="outline" onClick={toggle}>Units: {system}</Button></div>
    <div className="rounded-lg border bg-muted/50 p-4 text-sm leading-relaxed space-y-2"><p>Pull an initially straight steel pipe at the centre of a symmetric excavation while it remains pressurized. Both buried ends are ideal clamps; the excavated span is free of soil contact.</p><p>Compare uncertain initial states, calculate a prescribed movement, or explore lengths, displacements and support counts. Construction pressure and temperature stay constant; permanent assessment adds separate future operating cases. Optional frictionless supports allow lift-off and horizontal sliding. Horizontal-only pulling leaves vertical motion governed by weight and support contact.</p><p><strong>Separate temporary and permanent sequences.</strong> For permanent maintained deviation, select the dedicated elastic assessment below. HDPE and plastic steel are excluded. Temporary return assumes a reversible elastic path and restoration of support.</p></div>
    <div className="grid grid-cols-1 lg:grid-cols-[360px_minmax(0,1fr)] gap-6 items-start"><div className="space-y-4"><PermanentInputs input={input} onChange={v=>{engine.invalidate();setInput(v);}}/><ServiceInputs key={inputRevision} input={input} onChange={v=>{engine.invalidate();setInput(v);}}/><ServiceCsaInputs input={input} onChange={v=>{engine.invalidate();setInput(v);}}/></div>
      <div className="space-y-4 min-w-0"><section className="border rounded-lg bg-card p-4 space-y-3 sticky top-2 z-10 shadow-sm"><div className="flex gap-3 flex-wrap"><Button disabled={engine.busy} onClick={()=>engine.run(input)}>Calculate {input.mode==='direct'?'intervention':'exploratory search'}</Button>{engine.busy&&<Button variant="outline" onClick={engine.cancel}>Cancel</Button>}</div><p role="status" className="text-sm">{engine.busy?engine.progress:engine.report?'Calculation completed. Editing an input clears these results.':'Review the custom threshold and assumptions, then calculate.'}</p>{engine.error&&<p role="alert" className="text-destructive">{engine.error}</p>}</section>
        <section className="border rounded-lg bg-card p-4 space-y-3"><h2 className="font-semibold">Report identification</h2><ReportIdentityFields value={identity} onChange={setIdentity}/><p className="text-xs text-muted-foreground">Both names are required for PDF export. Export date and time are added automatically.</p></section>
        {engine.report?<ServiceResults report={engine.report} identity={identity}/>:<section className="border rounded-lg bg-card p-5 space-y-4"><h2 className="font-semibold">One intervention, several initial-state hypotheses</h2><p className="text-sm text-muted-foreground">Results will show the excavated state, support reactions, the target profiles, actuator forces, end reactions and the governing stress bound across the path. No scenario is treated as known merely because its extra force is zero.</p><svg viewBox="0 0 640 180" className="w-full" role="img" aria-label="Symmetric excavation with fixed ends and a central lifting point"><path d="M40 100H600" stroke="currentColor" opacity="0.4" strokeDasharray="6 5"/><path d="M40 100C180 100 190 35 320 35S460 100 600 100" fill="none" stroke="#f59e0b" strokeWidth="4"/><path d="M40 70V130M600 70V130" stroke="currentColor" strokeWidth="8"/><path d="M320 30V5m-6 8 6-8 6 8" fill="none" stroke="#f59e0b" strokeWidth="3"/><text x="120" y="155" fill="currentColor" fontSize="14">Half excavation length</text><text x="360" y="155" fill="currentColor" fontSize="14">Half excavation length</text></svg></section>}
        <section className="border rounded-lg bg-card p-4 text-sm space-y-2"><h2 className="font-semibold">Reference frameworks</h2><p>Active: user-defined elastic criterion.</p><p className="text-muted-foreground">Optional CSA Z662:2023 checks cover minimum nominal wall and the anchored pressure/temperature design state only. Lifting, bending/stability and Annex C remain unassessed. ASME B31.4/B31.8 and European requirements for Italy, France, Germany and Switzerland are planned extensions. No normative compliance verdict is available.</p></section>
      </div></div>
    <ServicePresets input={input} onLoad={v=>{engine.invalidate();setInput(v);setInputRevision(n=>n+1);}}/></>;
}
export default function InServicePage(){return <UnitProvider><div className="min-h-screen grid-background"><Header/><main className="container px-4 py-8 space-y-6"><Workspace/></main><Footer/></div></UnitProvider>;}
