const help:Record<string,string>={
 'Intervention type':'Temporary returns the pipe toward its initial configuration. Permanent follows support adjustment, backfill and equipment removal, then the operating cases. Example: a maintained relocation uses Permanent; steel must remain elastic.',
 'Initial supports during movement':'Keep means the initial supports stay at the original pipe-axis height while the equipment moves the pipe. Remove means they are progressively unloaded under equipment control first. Example: reuse the same jacks by unloading them before adjusting their heights.',
 'Release equipment':'Before backfill transfers the equipment load to the vertical supports first; lateral displacement may rebound. After backfill holds the target while soil is activated, then releases the equipment. This is a construction sequence, not an assurance that the target stays fixed.',
 'Support setting':'Fit calculates the support height separately for each initial-state scenario, without added preload. Common uses one physical set of heights for all scenarios. Example: enter surveyed pipe-axis heights in Common after comparing the fitted settings; zero means the original axis, not ground level.',
 'Final vertical tolerance':'Allowed difference between the target and final centre height, including the entered operating transitions. Starting example: 10 mm (0.394 in), not a code allowance or a recommended project tolerance. Smaller values make the position check more demanding.',
 'Final lateral tolerance':'Allowed sideways difference from the target at the centre in a controlled direction. Starting example: 10 mm (0.394 in); confirm the actual alignment tolerance. Vertical-only supports cannot prevent lateral rebound.',
 'Start x/L':'Start of this zone as a fraction of the FULL excavation length, from the left clamp. Example: 0.25 means 5 m from the left end of a 20 m excavation. Zones must cover 0 to 1 without gaps or overlap.',
 'End x/L':'End of this zone as a fraction of the FULL excavation length. Example: 0.5 ends at the centre, and 1 ends at the right clamp. Use the layout menu to generate adjoining zones automatically.',
 'Activation stage':'Order in which the backfill zones become active. Example: stage 1 at both ends and stage 2 in the centre. Equal numbers activate together; the number is an order, not a duration or a compaction-layer thickness.',
 'Initial bed gap':'Vertical distance from the pipe axis at zone activation to the lower contact reference. Default 0 mm means immediate bearing contact. Example: 5 mm represents a gap closed by 5 mm of downward movement. Do not enter pipe radius or trench depth.',
 'Permanent backfill load':'Added downward force PER UNIT PIPE LENGTH; separate from soil resistance and pipe/fluid weight. Starting example: 1 N/mm = 1 kN/m (about 5.71 lbf/in), not a geotechnical recommendation. Enter the applicable project load, accounting for cover, trench conditions and groundwater as appropriate.',
 'Temporary construction load':'Additional downward distributed load while this zone is activated; removed after that stage. Default 0 means no such load. Example: 2 N/mm = 2 kN/m. This simplified load does not model vibration, a point wheel load or compaction dynamics.',
 'Zone name':'Readable name printed in the report. Example: Left end, Central crossing, or Granular backfill zone A. The name alone does not supply material properties.',
 'Case name':'Name for an independent operating condition, such as Normal operation or Winter shutdown. A new case copies construction pressure, temperature and calculated fluid density as a starting point; adjust them to the intended case.',
 'Gauge pressure':'Internal pressure ABOVE atmospheric pressure. A new case starts at the construction value, without changing the original thermal reference. Example: 2000 kPa = 2 MPa. This is not automatically the CSA design pressure.',
 'Temperature':'Uniform pipe temperature for this operating case. Initially copied from construction, for example 20 °C (68 °F). It changes thermal force relative to the original scenario reference; it does not reset stress.',
 'Fluid density':'Fluid mass per volume at this case pressure and temperature. Initially copied from the calculated construction density. Example: 40 kg/m³ for a known gas state; this number is not valid for every gas pressure or composition. Recalculate or enter project data when conditions change.',
 'Source / justification':'Record where the curve comes from, including the report, revision, location and applicability. Example: Geotechnical report GT-12, rev B, table 6. Built-in examples are sensitivity inputs, not measurements or a soil classification.',
 'Backfill layout':'Generate zone extents and activation order automatically. Uniform: one zone. Halves: left then right. Ends first: both outer quarters, then the middle half. Applying a layout replaces existing zones and copies the first zone properties to each new zone.',
 'Soil response example':'Illustrative force–movement curves for trying the workflow. Flexible, intermediate and stiff are relative sensitivity cases, not sand/clay/gravel classes. A stiffer soil can increase pipe stress while reducing displacement; no example is universally conservative.',
 'Starting values reviewed':'Confirm only after checking the example soil curves, loads, gaps, tolerances, support heights and operating cases against project information. Until then, numerical results may be explored but stress and position verdicts are not evaluated. This confirmation is not normative approval.',
};
export function permanentHelp(title:string):string|undefined{
 if(help[title])return help[title];
 if(/^Pair position/.test(title))return 'Left support position divided by FULL excavation length. The second support is mirrored. Example: 0.25 creates a pair at one-quarter and three-quarters of the span. Pairs are numbered from the centre outward; positions stay fixed during the sequence.';
 if(/^Pair \d+ height/.test(title))return 'Common absolute pipe-axis elevation relative to the original straight axis. Starting value 0 means the original level. Positive is upward; this is not jack extension. A height above the calculated pipe position introduces preload. Prefer Fit first to obtain useful settings.';
 if(/^(axial|lateral|down|up) displacement/.test(title))return 'Relative pipe–soil movement at this curve point, not the commanded centre displacement. The first point is (0,0); movements must increase. Example: 20 mm with 20 N/mm resistance gives a secant stiffness of 1 N/mm². The last point is the documented movement limit.';
 if(/^(axial|lateral|down|up) resistance/.test(title))return 'Positive magnitude of distributed soil resistance at this curve point, NOT stress and NOT total force. 1 N/mm = 1 kN/m. Example: 20 N/mm over 1 m corresponds to 20 kN. Values cannot decrease; reaching terminal resistance prevents verified retention. Axial/lateral act both ways; bearing and uplift have separate curves.';
 return undefined;
}
